### ISSUE TITLE
fmtver - Is it important?

### ISSUE THREAD

**Issue by zemmyang** [donmai-me/WannaCRI#11]
I'm working on a reader for the USM files used in Deus Ex Human Revolution, but I kept giving me an error with the format version of the `@SFV` chunks

I commented out https://github.com/donmai-me/WannaCRI/blob/master/wannacri/usm/usm.py#L187 and https://github.com/donmai-me/WannaCRI/blob/master/wannacri/usm/usm.py#L251 and I got the demuxed video and audio just fine, so I'm wondering if it's important to check for the fmtver key at all.

BTW, I also had to add
```
        SUBTITLE = bytearray("@SBT", "UTF-8")
        CUE = bytearray("@CUE", "UTF-8")
```
to the ChunkType enum

**Comment by donmai-me** [comment]
It's just metadata so it's not really needed. I should have done checks if `get`ting the value of a key returns `None`. Since it's a western game, I'd assume the usm is made from Scaleform's encoder. Also yes I'd need to add the other chunktypes. Thank you for pointing that out.

**Comment by donmai-me** [comment]
Should be fixed in commit 38e883b let me know if I missed anything

**Comment by donmai-me** [comment]
Missed that one, should be fixed in the latest commit. Thanks for the heads up.

**Comment by zemmyang** [comment]
just tested - works now. thanks!
